### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by daPhipz**
During debugging for #2 I noticed these two small things.

### CODE REVIEW

**Review by ricktimmis — APPROVED** [review]
Ah ha, yes that's a definite mistake, my bad I was rushing to got it out.
Looks great
Ship It!

**Comment by ricktimmis** [comment]
Go ahead merge it @daPhipz 🥰

**Comment by daPhipz** [comment]
I can't - I don't have write access to this repo :see_no_evil:

**Comment by ricktimmis** [comment]
Apologies @daPhipz no problem, I've merged it. Will look in more depth at the issue you identified this evening 😉

**Comment by daPhipz** [comment]
Thanks!
I am looking at it right now.
I am by no means a pro when it comes to programming/scripting though, so this may be low quality 😅
I'll file a draft PR once I'm pleased with my code.

**Pull request merged**
