### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by daPhipz**
This does not yet reflect the changes made in #4.
I will of course update the README when these changes land! ;)

### CODE REVIEW

**Comment by daPhipz** [comment]
Well, there actually wasn't much that needed updating. LGTM as far as I am concerned ;)

**Comment by ricktimmis** [comment]
I thought it would be good to capture your improvement ideas as Github Issues, hopefully other might get involved too.

- https://github.com/kubuntu-team/KubuQA/issues/7
- https://github.com/kubuntu-team/KubuQA/issues/8
- https://github.com/kubuntu-team/KubuQA/issues/9
- https://github.com/kubuntu-team/KubuQA/issues/10

In the interim, I've made a small change to remove the Idea's task list in favour of the Issues Link.

**Review by ricktimmis — APPROVED** [review]
In between writing my comment, and making the commit. I changed my mind and went for the best of both worlds, incorporating links from the Ideas list back to the Issues in Github. I think that stands and even better chance of getting others involved.

**Comment by ricktimmis** [comment]
Thanks Again @daPhipz great stuff!!!

**Pull request merged**
